### ISSUE TITLE
Attempt to call "addInit" of class "GraphAware\Neo4j\OGM\Common\Collection"

### ISSUE THREAD

**Issue by Nyholm** [graphaware/neo4j-php-ogm#46]
I've got this error a couple of times. I have not found the cause for it yet. Im writing this issue so I do not forget. 

```
Error: Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: 
  Attempted to call an undefined method named "addInit" of class "GraphAware\Neo4j\OGM\Common\Collection". in /home/sites/xxx/releases/20161114162645/vendor/graphaware/neo4j-php-ogm/src/Repository/BaseRepository.php:745

Stack trace:
#0 /home/sites/xxx/releases/20161114162645/vendor/graphaware/neo4j-php-ogm/src/Repository/BaseRepository.php(429): GraphAware\Neo4j\OGM\Repository\BaseRepository->setInversedAssociation(Object(AppBundle\Entity\Location), Object(AppBundle\Entity\User), 'user')
#1 /home/sites/xxx/releases/20161114162645/vendor/graphaware/neo4j-php-ogm/src/Repository/BaseRepository.php(401): GraphAware\Neo4j\OGM\Repository\BaseRepository->hydrate(Object(GraphAware\Neo4j\Client\Formatter\RecordView))
#2 /home/sites/xxx/releases/20161114162645/vendor/graphaware/neo4j-php-ogm/src/Repository/BaseRepository.php(315): GraphAware\Neo4j\OGM\Repository\BaseRepo' in /home/sites/xxx/releases/20161114162645/vendor/graphaware/neo4j-php-ogm/src/Repository/BaseRepository.php:745
```

**Comment by ikwattro** [comment]
Thx I know where it comes from and this implementation will be removed in #39 .

**Comment by Nyholm** [comment]
Okey. Awesome

**Comment by ikwattro** [comment]
Fixed
